name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:  
  test:
    strategy:
        fail-fast: false
        matrix:
          os:
            - ubuntu-latest
          go:
            - 1.26

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}

    - name: Install dependencies
      run: |
        go mod download

    - name: Run Unit tests
      run: |
        go test -race -covermode atomic -coverprofile=covprofile ./...

    - name: Install goveralls
      run: go install github.com/mattn/goveralls@latest

    - name: Send coverage
      env:
        COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: goveralls -coverprofile=covprofile -service=github